---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "workload-app.serviceAccountName" . }}
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "workload-app.labels" . | nindent 4 }}
{{- end }}