---
app:
  name: backend-1
  namespace: w2w-demo
  replicas: 1

image:
  repository: 668558765449.dkr.ecr.us-west-2.amazonaws.com/mwi-demo-10bbb2a
  tag: "backend-pr-2-f113e8b8"
  pullPolicy: Always

env:
  BACKEND_SOCKET_PATH: "unix:///run/tbot/sockets/workload.sock"
  BACKEND_APPROVED_CLIENT_SPIFFEID: "spiffe://mwidemo.cloud.gravitational.io/w2w-demo/web"
  BACKEND_NAME: "Backend 1"
  BACKEND_INFRA: "kubernetes"
  BACKEND_PORT: "3000"

service:
  type: LoadBalancer
  port: 443
  targetPort: 3000

serviceAccount:
  create: true
  name: backend-1

volumes:
  tbotSockets:
    mountPath: /run/tbot/sockets
    hostPath: /run/tbot/sockets
    readOnly: false